### PR TITLE
imp(derive): add Clone directive to ProfilerGuardBuilder

### PR DESCRIPTION
**Pull request by omarabid**

### CODE REVIEW

**Comment by YangKeao** [comment]
Please sign-off the commit.

**Comment by omarabid** [comment]
Signed-off! (though it was committed by Github and I thought it signs these off automatically).

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by omarabid** [comment]
@YangKeao Thanks. Running the library now (https://github.com/omarabid/pyroscope/blob/master/Cargo.toml) from the master branch. Do you have any ETA for a new release, as the latest one (0.6.0) doesn't have the ProfilerGuardBuilder object.

**Comment by YangKeao** [comment]
> @YangKeao Thanks. Running the library now ([omarabid/pyroscope@`master`/Cargo.toml](https://github.com/omarabid/pyroscope/blob/master/Cargo.toml?rgh-link-date=2021-12-22T18%3A44%3A58Z)) from the master branch. Do you have any ETA for a new release, as the latest one (0.6.0) doesn't have the ProfilerGuardBuilder object.

The latest version is 0.6.1, which has the `ProfilerGuardBuilder` object. 

It seems that it doesn't add a tag/release on the github. However, this repo doesn't allow push to the master directly now 😢 . I will contact others in tikv org to know how to push tags/release to the master.

**Comment by omarabid** [comment]
@YangKeao Additionally, the tagged version will need to be pushed to crates.io. I'm not aware of crates.io pulling the changes automatically from Github.

**Comment by YangKeao** [comment]
@omarabid The package on `crates.io` is always pushed by me manually, and the `0.6.1` has already been pushed about two months ago (you can check it [here](https://crates.io/crates/pprof))

**Comment by omarabid** [comment]
@YangKeao If you pushed two months ago then the latest changes (in master) are not in 0.6.1 :) Can you push again to crates.io (and maybe increment the version to 0.6.2?)

**Comment by YangKeao** [comment]
> @YangKeao If you pushed two months ago then the latest changes (in master) are not in 0.6.1 :) Can you push again to crates.io (and maybe increment the version to 0.6.2?)

Oops, sorry. I haven't realized that the [`pyroscope`](https://github.com/omarabid/pyroscope) has been ready to publish (I thought the new version of pprof-rs could wait until the development finished, in case the [`pyroscope`] needs further modification on `pprof-rs`). Now, 0.6.2 has been published.

BTW, do you mind me to review/comment codes for the [`pyroscope`](https://github.com/omarabid/pyroscope)? I will take a look at the existing codes tomorrow morning (as it's 00:10 and I need to sleep :sleeping_bed:)

**Comment by omarabid** [comment]
@YangKeao I modified the original code to only use report() by the ProfilerGuard. So I only needed the Clone tag to be able to clone ProfilerGuardBuilder. I still think pprof-rs should focus only on generating the reports, and leave the consumption of these reports to other libraries. This helps making this library focus on one thing (profiling) and let the end-developer decides what to do with data.

**Comment by omarabid** [comment]
Also thank you for the quick release and push :)

**Pull request merged**
