### PR TITLE
Adds timing info to each sample

### PR DESCRIPTION
**Pull request by viglia**
At the moment we only have timing info at `Report` level. We don't have more fine grained timing info for the samples collected.

This PR aims at adding timing info (`sample_timestamp`) to the samples collected.

### CODE REVIEW

**Review by YangKeao — COMMENTED** [review]
Good! As the `clock_gettime` is usually fast (with vDSO in Linux), I think it won't have too much performance degradation. I'll also bench it to make sure.

BTW, please modify the `CHANGELOG.md`

Rest LGTM

**Comment by viglia** [comment]
@YangKeao thanks for looking over this PR. 

I've updated the `CHANGELOG.md` as requested.

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by viglia** [comment]
@YangKeao thanks for merging the other PR.

I think this is good to go as well?

**Pull request merged**
