### PR TITLE
*: support rust-protobuf

### PR DESCRIPTION
**Pull request by BusyJay**
Close #23.

### CODE REVIEW

**Comment by YangKeao** [comment]
The GitHub action should be updated to not enable all features for Clippy.

**Comment by BusyJay** [comment]
It's tested in TiKV.

**Review by YangKeao — APPROVED** [review]
LGTM.

@BusyJay Please update the `CHANGELOG.md`, then it can be merged 😃

**Comment by BusyJay** [comment]
I use a new format of changelog that reference PR instead of authors. This may be more informative.

**Comment by YangKeao** [comment]
> I use a new format of changelog that reference PR instead of authors. This may be more informative.

Good.

**Comment by BusyJay** [comment]
Note this is a breaking change, and should not be released as a patch version. Though TiKV can use url directly.

**Pull request merged**
