### PR TITLE
fix: handle potentially unaligned frame pointer

### PR DESCRIPTION
**Pull request by gen-xu**
this PR addressed the issue https://github.com/tikv/pprof-rs/issues/216

### CODE REVIEW

**Comment by alindima** [comment]
@YangKeao this is an important PR that prevents using pprof-rs with frame poitner unwinding, could you please approve it?

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Sorry for the late reply and thanks for your contribution! Once you signed-off the commit, I'll merge this pull request ❤️ .

**Comment by gen-xu** [comment]
@YangKeao just signed off

**Pull request merged**
