### PR TITLE
Fix build for aarch64-linux-android

### PR DESCRIPTION
**Pull request by flxo**
Enable building pprof for target_os = `android`.

### CODE REVIEW

**Comment by YangKeao** [comment]
Do you have a demo program to run `pprof-rs` on Android? It sounds really interesting.

**Comment by flxo** [comment]
> Do you have a demo program to run `pprof-rs` on Android? It sounds really interesting.

I used the examples for a quick check. Looks like it works as expected. Not a bit surprise since google ships [simpleperf](https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/README.md) for years which does basically the same.

**Comment by YangKeao** [comment]
Could you rebase on the master? I believe the CI failing has been fixed on the latest master :thinking:

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Thanks again for your contribution. I'll schedule the version bump tonight (Mar 22. 20:00, UTC+8)

**Comment by flxo** [comment]
Thanks @YangKeao Any change that we add `aarch64-linux-android` in the GH actions?

**Pull request merged**
