### PR TITLE
allow passing custom flamegraph options

### LINKED ISSUE #38: Can't see full method names in flamegraph
In order to make sense of the kind of data that a profiler produces, some sort of visualization such as a flamegraph is essentially mandatory. Yet, when I generate a flamegraph from this tool, all the method names state with the module path, which makes seeing which method it is impossible, which is blocking me from accessing any useful data.

### PR DESCRIPTION
**Pull request by noahols**
Added a new method flamegraph_with_options to Report

This could be used to resolve #38 

Signed-off-by: Noah Olson <noah.olson@protonmail.ch>

### CODE REVIEW

**Comment by YangKeao** [comment]
Wow. Thanks for your contribution :beers:.  

`cargo fmt` and a `sign-off` is needed. As there is only one commit here, you can use `git commit --amend -s` and `git push -f` to add a `sign-off` for this commit.

**Comment by noahols** [comment]
Sorry, I didn't realize you use rust fmt. Thanks for your help.

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
`v0.4.1` has included this feature. :beers:

**Pull request merged**
